#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version = 2
final_space = true
console_title_template = '{{ .Shell }} in {{ .Folder }}'

# Path configuation
[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'path'
    style = 'plain'
    background = 'transparent'
    foreground = 'blue'
    template = '{{ .Path }}'    

    [blocks.segments.properties]
      style = 'full'

  # Git configuration 
  [[blocks.segments]]
    type = 'git'
    style = 'plain'
    foreground = 'p:grey'
    background = 'transparent'    
    template = ' {{ .HEAD }}{{ if or (.Working.Changed) (.Staging.Changed) }}*{{ end }} <cyan>{{if gt .Behind 0}}↓{{ end }}{{ if gt .Ahead 0}}↑{{ end }}</>'

    [blocks.segments.properties]
      fetch_status = true
      commit_icon = '@'

# Display execution time for 5ms or longer
[[blocks]]
  type = 'rprompt'
  overflow = 'hidden'

  [[blocks.segments]]
    type = 'executiontime'
    style = 'plain'
    foreground = 'yellow'
    background = 'transparent'
    template = '{{ .FormattedMs }}'

    [blocks.segments.properties]
      threshold = 5000
      style = 'lucky7'

# Text block - prompt
[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    foreground_templates = [
      '{{ if gt .Code 0 }}red{{ end }}',
      '{{ if eq .Code 0 }}magenta{{ end }}',
    ]
    background = 'transparent'
    template = '❱'

# Transient prompt config
[transient_prompt]
  foreground_templates = [
      '{{ if gt .Code 0 }}red{{ end }}',
      '{{ if eq .Code 0 }}magenta{{ end }}',
  ]
  background = 'transparent'
  template = '❱ '

# Multi line commands
[secondary_prompt]
  foreground = 'magenta'
  background = 'transparent'
  template = '❱❱ '

# Reusable colors
[palette]
  grey = '#6c6c6c' 
